### ISSUE TITLE
question about aligning during inference

### ISSUE THREAD

**Issue by shuangshuangguo** [JosephKJ/ELI#5]
From the following code:
https://github.com/JosephKJ/ELI/blob/main/detection/detectron2/modeling/roi_heads/roi_heads.py#L558
It seems that at the inference time, we need to know the gt class of objects in the image.
Please correct me if I am wrong.

**Comment by BinahHu** [comment]
I think the author assumes we know a binary label about whether the input belongs to current or previous tasks so the aligner is able to work. This is stated in section 3.2.2 of the paper.

Since the bias in incremental learning is mainly towards current task, using an aligner to split features of current task and previous tasks should be helpful.

However, with such a binary label, this is not a strict class incremental learning setting and the comparison to other CIL methods is unfair anyway.

**Comment by shuangshuangguo** [comment]
@BinahHu Yes, I agree with you. Actually for the practical application, we do not know whether the testing image belongs to current or previous tasks.

**Comment by JosephKJ** [comment]
We can learn a simple binary classifier to automate this decision making.
